



class Payment{


    constructor({
        id="",
        label="",
        loan_id=1,
        amount=50000,
        total_amount=0,
        interest_amount=0,
        paid_amount=0,
        left_amount=0,
        late_days=1,
        payment_date="",
        status="pending",
        payment_method="cash",
        notes="",
        paid_date='',
        created_at="",
        updated_at="",
        user_id="",
        loan_label,

}){


        this.id=id
        this.label=label
        this.loan_id=loan_id
        this.amount=amount
        this.total_amount=total_amount
        this.interest_amount=interest_amount
        this.paid_amount=paid_amount
        this.left_amount=left_amount
        this.late_days=late_days
        this.paid_date = paid_date
       
      
        this.payment_date= payment_date
        
        this.loan_label
        
        this.status=status,
        this.payment_method=payment_method,
        this.notes=notes,
        this.created_at=created_at,
        this.updated_at=updated_at,
        this.user_id=user_id
        
    }

    async update(columns,values){


        console.log(columns)
        console.log(values)
      //  console.log(columns)
        try {
            const result = await window.electron.database.update('payments',{
                columns:columns,
                where:`id = ?`
            },[...values,this.id])

            console.log(result)

            return true
        } catch (error) {
            console.log(error)
            return false
        }
        
    }


    async insert(){

        try {
            
           /*  this.interest_amount = this.amount*interest_rate/100
            this.total_amount = this.amount+interest_amount
 */
           const ob = this.paymentToObject()

           
            
            delete ob.id // remove id if exists, it will be auto generated by the database
            delete ob.created_at // remove created_at if exists, it will be auto generated by the database
            delete ob.updated_at // remove updated_at if exists, it will be auto generated by the
            delete ob.loan_label

            ob.total_amount = Math.floor(ob.total_amount)
            //console.log(ob,"asdasdasd")
             //TODO: save user in the database
            const result = await window.electron.database.insert('payments', 
            Object.keys(ob), 
                Object.values(ob))

                //console.log(result)
            this.id = result.lastInsertRowId

        return result
                
        } catch (error) {
            
            console.log(error)
            
            return {
                error:error.message
            }
        }

         

        
    }


    paymentToObject(){

        
        return {
        id:this.id,
        label:this.label,
        loan_id:this.loan_id,
        amount:this.amount,
        total_amount:this.total_amount,
        interest_amount:this.interest_amount ,
        late_days:this.late_days,
        notes:this.notes,
        status:this.status ,
        user_id:this.user_id,
        payment_date:this.payment_date,
        payment_method:this.payment_method,
        paid_amount:this.paid_amount,
        left_amount :this.left_amount,
        paid_date:this.paid_date,
        loan_label:this.loan_label
        }
    }


}


export default Payment;